spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: root
    password: db123456
# default port for eureka server
server:
  port: 8750

# don't register eureka server service in eureka service register
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

